### ISSUE TITLE
`DocumentIndexing` fails for the Semantic Search Stack

### ISSUE THREAD

**Issue by uzaymacar** [aws-samples/aws-genai-llm-chatbot#14]
I've tried this a few times: Git cloning the original repo and following the steps mentioned in the README, I get the following error:

```
11:34:24 PM | CREATE_FAILED        | AWS::CloudFormation::Stack                  | DocumentIndexingSt...ckResourceFCFB528D
```

where `DocumentIndexing` fails within the semantic search stack.

The only change I did is to set [this line](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/25a572b88016ca4993e4488ca8a6ca07ebc74687/bin/aws-genai-llm-chatbot.ts#L13) to `true`. Any ideas?

**Comment by uzaymacar** [comment]
Even when I don't set semantic search to `true`, the pipeline still fails, see the following error message:

> Embedded stack arn:aws:cloudformation:eu-west-2:762225441503:stack/HibiGPT-ChatBotStack-ChatBotBackendStackNestedStackChatBotBacke
ndStackNestedStackResou-11NAOMQI64XV0/c118de30-3c40-11ee-8a7a-02699e793908 was not successfully created: The following resource(s)
failed to create: [SendMessageFunctionA37DCB9D].

**Comment by bigadsoleiman** [comment]
HI @uzaymacar I suggest you to experiment with the new version we just released today and reach out if you still experience issues.

**Comment by uzaymacar** [comment]
Thanks for the update @bigadsoleiman, with the new version I get the following error:

```
node_modules/csstype/index.d.ts(14054,16): error TS1010: '*/' expected.
/Users/uzaymacar/Projects/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/core/lib/asset-staging.js:2
`),localBundling=options.local?.tryBundle(bundleDir,options),!localBundling){const assetStagingOptions={sourcePath:this.sourcePath,bundleDir,...options};switch(options.bundlingFileAccess){case bundling_1.BundlingFileAccess.VOLUME_COPY:new asset_staging_1.AssetBundlingVolumeCopy(assetStagingOptions).run();break;case bundling_1.BundlingFileAccess.BIND_MOUNT:default:new asset_staging_1.AssetBundlingBindMount(assetStagingOptions).run();break}}}catch(err){const bundleErrorDir=bundleDir+"-error";throw fs.existsSync(bundleErrorDir)&&fs.removeSync(bundleErrorDir),fs.renameSync(bundleDir,bundleErrorDir),new Error(`Failed to bundle asset ${this.node.path}, bundle output is located at ${bundleErrorDir}: ${err}`)}if(fs_1.FileSystem.isEmpty(bundleDir)){const outputDir=localBundling?bundleDir:AssetStaging.BUNDLING_OUTPUT_DIR;throw new Error(`Bundling did not produce any output. Check that content is written to ${outputDir}.`)}}calculateHash(hashType,bundling,outputDir){if(hashType==assets_1.AssetHashType.CUSTOM||hashType==assets_1.AssetHashType.SOURCE&&bundling){const hash=crypto.createHash("sha256");return hash.update(this.customSourceFingerprint??fs_1.FileSystem.fingerprint(this.sourcePath,this.fingerprintOptions)),bundling&&hash.update(JSON.stringify(bundling)),hash.digest("hex")}switch(hashType){case assets_1.AssetHashType.SOURCE:return fs_1.FileSystem.fingerprint(this.sourcePath,this.fingerprintOptions);case assets_1.AssetHashType.BUNDLE:case assets_1.AssetHashType.OUTPUT:if(!outputDir)throw new Error(`Cannot use \`${hashType}\` hash type when \`bundling\` is not specified.`);return fs_1.FileSystem.fingerprint(outputDir,this.fingerprintOptions);default:throw new Error("Unknown asset hash type.")}}}exports.AssetStaging=AssetStaging,_a=JSII_RTTI_SYMBOL_1,AssetStaging[_a]={fqn:"aws-cdk-lib.AssetStaging",version:"2.92.0"},AssetStaging.BUNDLING_INPUT_DIR="/asset-input",AssetStaging.BUNDLING_OUTPUT_DIR="/asset-output",AssetStaging.assetCache=new cache_1.Cache;function renderAssetFilename(assetHash,extension=""){return`asset.${assetHash}${extension}`}function determineHashType(assetHashType,customSourceFingerprint){const hashType=customSourceFingerprint?assetHashType??assets_1.AssetHashType.CUSTOM:assetHashType??assets_1.AssetHashType.SOURCE;if(customSourceFingerprint&&hashType!==assets_1.AssetHashType.CUSTOM)throw new Error(`Cannot specify \`${assetHashType}\` for \`assetHashType\` when \`assetHash\` is specified. Use \`CUSTOM\` or leave \`undefined\`.`);if(hashType===assets_1.AssetHashType.CUSTOM&&!customSourceFingerprint)throw new Error("`assetHash` must be specified when `assetHashType` is set to `AssetHashType.CUSTOM`.");return hashType}function calculateCacheKey(props){return crypto.createHash("sha256").update(JSON.stringify(sortObject(props))).digest("hex")}function sortObject(object){if(typeof object!="object"||object instanceof Array)return object;const ret={};for(const key of Object.keys(object).sort())ret[key]=sortObject(object[key]);return ret}function singleArchiveFile(directory){if(!fs.existsSync(directory))throw new Error(`Directory ${directory} does not exist.`);if(!fs.statSync(directory).isDirectory())throw new Error(`${directory} is not a directory.`);const content=fs.readdirSync(directory);if(content.length===1){const file=path.join(directory,content[0]),extension=getExtension(content[0]).toLowerCase();if(fs.statSync(file).isFile()&&ARCHIVE_EXTENSIONS.includes(extension))return file}}function determineBundledAsset(bundleDir,outputType){const archiveFile=singleArchiveFile(bundleDir);switch(outputType===bundling_1.BundlingOutput.AUTO_DISCOVER&&(outputType=archiveFile?bundling_1.BundlingOutput.ARCHIVED:bundling_1.BundlingOutput.NOT_ARCHIVED),outputType){case bundling_1.BundlingOutput.NOT_ARCHIVED:return{path:bundleDir,packaging:assets_1.FileAssetPackaging.ZIP_DIRECTORY};case bundling_1.BundlingOutput.ARCHIVED:if(!archiveFile)throw new Error("Bundling output directory is expected to include only a single archive file when `output` is set to `ARCHIVED`");return{path:archiveFile,packaging:assets_1.FileAssetPackaging.FILE,extension:getExtension(archiveFile)}}}function getExtension(source){for(const ext of ARCHIVE_EXTENSIONS)if(source.toLowerCase().endsWith(ext))return ext;return path.extname(source)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ^
Error: Failed to bundle asset AwsGenaiLllmChatbotStack/WebInterface/AwsExportsDepolyment/Asset1/Stage, bundle output is located at /Users/uzaymacar/Projects/aws-genai-llm-chatbot/cdk.out/asset.52090184a9e1cc864b6bbde5891b833bca13dd0dedadd26b0cc757678c1d641c-error: Error: docker exited with status 2
--> Command: docker run --rm -u "501:20" -v "/Users/uzaymacar/Projects/aws-genai-llm-chatbot/lib/user-interface/react:/asset-input:delegated" -v "/Users/uzaymacar/Projects/aws-genai-llm-chatbot/cdk.out/asset.52090184a9e1cc864b6bbde5891b833bca13dd0dedadd26b0cc757678c1d641c:/asset-output:delegated" -w "/asset-input" "public.ecr.aws/sam/build-nodejs18.x" sh -c "npm --cache /tmp/.npm install && npm --cache /tmp/.npm run build && cp -aur /asset-input/dist/* /asset-output/"
    at AssetStaging.bundle (/Users/uzaymacar/Projects/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/core/lib/asset-staging.js:2:603)
    at AssetStaging.stageByBundling (/Users/uzaymacar/Projects/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:4544)
    at stageThisAsset (/Users/uzaymacar/Projects/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2005)
    at Cache.obtain (/Users/uzaymacar/Projects/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/core/lib/private/cache.js:1:242)
    at new AssetStaging (/Users/uzaymacar/Projects/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2400)
    at new Asset (/Users/uzaymacar/Projects/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:736)
    at Object.bind (/Users/uzaymacar/Projects/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/aws-s3-deployment/lib/source.js:1:1185)
    at /Users/uzaymacar/Projects/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3096
    at Array.map (<anonymous>)
    at new BucketDeployment (/Users/uzaymacar/Projects/aws-genai-llm-chatbot/node_modules/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.js:1:3077)
```

**Comment by bigadsoleiman** [comment]
That appears to be an issue in bundling the UI within the docker container.

Can you share which OS/arch are you trying to deploy from and node version are you using?

In the meantime, we [added](https://github.com/aws-samples/aws-genai-llm-chatbot/commit/1479906c03b731f89bf811cfea4949f7a189ba09) an option that tries to build locally (not in a Docker container) first.

**Comment by uzaymacar** [comment]
Thanks @bigadsoleiman will check it out. Meanwhile, I'm using node version `v18.12.1` and I'm on a MacBook with `21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64`

**Comment by uzaymacar** [comment]
This time I got as far as to deploying the cloud formation stack, however now I face the following error:

```
9:43:54 PM | CREATE_FAILED        | AWS::Lambda::Function                           | AuroraPgVector/Doc...g/DocumentIndexing
Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 97bb525d-36a0-4409-8d1c-2e2
8a568f183)" (RequestToken: de349f41-536d-d110-1f43-0c0a66f3a6da, HandlerErrorCode: InvalidRequest)
```

Assuming this is an easy to fix parameter, looking into it now.

**Comment by uzaymacar** [comment]
I can confirm that the issue is solved with the `local` approach, after I decrease the `memorySize` parameters as described in my [previous comment](https://github.com/aws-samples/aws-genai-llm-chatbot/issues/14#issuecomment-1685109915).

**Comment by bigadsoleiman** [comment]
Thanks @uzaymacar 

I've [updated](https://github.com/aws-samples/aws-genai-llm-chatbot/commit/6dc6f3802ca5cf9ad19c5ed7e0c5c8f169e5de08) the `memorySize` to address the latter issue as well.
