### ISSUE TITLE
is it possible to replace Sagemaker by Bedrock

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws-samples/aws-genai-llm-chatbot#481]
Dear all,

I'm trying to get rid of Sagemaker and replace it by Bedrock (non-serverless vs serverless optimization).
Is it possible at all ?

Simple change
sed -i 's|"provider": "sagemaker"|"provider": "bedrock"|' bin/config.json
does NOT do the job.
In this case I have an error message during deployment:

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
dist/assets/index-86466b77.js   2,091.61 kB │ gzip: 579.32 kB
✓ built in 26.55s
/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/cdk-nag/src/nag-suppressions.ts:98
    pathArray.forEach((p) => {
              ^
Error: Suppression path "/genaiGenAIChatBotStack/RagEngines/SageMaker/Model/MultiAB24A/CodeBuildRole/DefaultPolicy/Resource" did not match any resource.
 This can occur when a resource does not exist or if a suppression is applied before a resource is created.
    at /home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/cdk-nag/src/nag-suppressions.ts:115:15
    at Array.forEach (<anonymous>)
    at Function.addResourceSuppressionsByPath (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/cdk-nag/src/nag-suppressions.ts:98:15)
    at new AwsGenAILLMChatbotStack (/home/ubuntu/environment/aws-genai-llm-chatbot/lib/aws-genai-llm-chatbot-stack.ts:273:25)
    at Object.<anonymous> (/home/ubuntu/environment/aws-genai-llm-chatbot/bin/aws-genai-llm-chatbot.ts:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module.m._compile (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
[11:35:39] failed command: npx ts-node --prefer-ts-exts bin/aws-genai-llm-chatbot.ts
[11:35:39] Notices refreshed
Subprocess exited with error 1
[11:35:39] Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/home/ubuntu/environment/aws-genai-llm-chatbot/node_modules/aws-cdk/lib/index.js:430:50676)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess.emit (node:domain:488:12)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

best regards
Alexey Shishkin

**Comment by bigadsoleiman** [comment]
It depemds which version of this repo you are running.

If you have a fairly recent one you should be able to re-run `npm run config` (previously `npm run create`) deselect sagemaker models, enable bedrock and redeploy. Otherwise you're better off destroy, pull latest changes and deploy.

**Comment by nasirtrekker** [comment]
> It depemds which version of this repo you are running.
> 
> If you have a fairly recent one you should be able to re-run `npm run config` (previously `npm run create`) deselect sagemaker models, enable bedrock and redeploy. Otherwise you're better off destroy, pull latest changes and deploy.

if do npm run config will the current workspace/data disappeared?
