### ISSUE TITLE
RAG OpenSearch deployment fails with "image size exceeds 10 GiB limit)

### ISSUE THREAD

**Issue by schadem** [aws-samples/aws-genai-llm-chatbot#59]
deploying RAG OpenSearch and got:

```
AwsGenaiLllmChatbotStack: creating CloudFormation changeset...
9:49:14 AM | CREATE_FAILED        | AWS::Lambda::Function                           | OpenSearchVectorSe...exDocument36B
9A569
Resource handler returned message: "Lambda function AwsGenaiLllmChatbotStack-OpenSearchVectorSearchInd-ncsjPLa7PulW reac
hed terminal FAILED state due to InvalidImage(SizeLimitExceeded: Uncompressed container image size exceeds 10 GiB limit)
and failed to stabilize" (RequestToken: 015e710a-ca90-5ada-4a74-c4b7ca44b586, HandlerErrorCode: NotStabilized)


 ❌  AwsGenaiLllmChatbotStack failed: Error: The stack named AwsGenaiLllmChatbotStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Lambda function AwsGenaiLllmChatbotStack-OpenSearchVectorSearchInd-ncsjPLa7PulW reached terminal FAILED state due to InvalidImage(SizeLimitExceeded: Uncompressed container image size exceeds 10 GiB limit) and failed to stabilize" (RequestToken: 015e710a-ca90-5ada-4a74-c4b7ca44b586, HandlerErrorCode: NotStabilized)
    at FullCloudFormationDeployment.monitorDeployment (/home/ec2-user/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:467:10232)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/ec2-user/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:470:179911)
    at async /home/ec2-user/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:470:163159
```

**Comment by schadem** [comment]
closing because duplicate of issue #38
