### ISSUE TITLE
Error when crawling website: ValueError: A string literal cannot contain NUL (0x00) characters.

### ISSUE THREAD

**Issue by awsjohns** [aws-samples/aws-genai-llm-chatbot#82]
[WARNING]	2023-10-04T15:08:35.577Z	718cab60-34cb-4d0d-a349-35064164bc36	Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
**[ERROR] ValueError: A string literal cannot contain NUL (0x00) characters.**
Traceback (most recent call last):
  File "/opt/python/aws_lambda_powertools/logging/logger.py", line 442, in decorate
    return lambda_handler(event, context, *args, **kwargs)
  File "/var/task/index.py", line 30, in lambda_handler
    genai_core.websites.crawler.crawl_urls(
  File "/opt/python/genai_core/websites/crawler.py", line 58, in crawl_urls
    genai_core.chunks.add_chunks(
  File "/opt/python/genai_core/chunks.py", line 50, in add_chunks
    result = genai_core.aurora.chunks.add_chunks_aurora(
  File "/opt/python/genai_core/aurora/chunks.py", line 43, in add_chunks_aurora
    cursor.execute(

**Comment by dairiley** [comment]
Can you share the URL you were crawling?
